name = "mergeblitz-bot"
main = "src/index.js"
compatibility_date = "2026-07-01"

kv_namespaces = [
  { binding = "MERGEBLITZ_KV", id = "899f359f90eb4f9b998874450996bb4e" }
]

[vars]
WEBAPP_URL = "https://raskassa33.github.io/mergeblitz/"
BOT_USERNAME = "Mergeblitzzbot"
